language: generic
sudo: required
services: 
    - docker

before_install:
    - docker build -t jagwinder/react-test -f ./client/Dockerfile.dev ./client
    
script:
    - docker run -e CI=true jagwinder/react-test npm test
    
after_success:
    - docker build -t jagwinder/multi-client ./client
    - docker build -t jagwinder/multi-nginx ./nginx
    - docker build -t jagwinder/multi-server ./server
    - docker build -t jagwinder/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push jagwinder/multi-client
    - docker push jagwinder/multi-nginx
    - docker push jagwinder/multi-server
    - docker push jagwinder/multi-worker  

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-1-647874871378"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY    
