sudo: required
services: 
    - docker

before_install:
    - docker build -t jagwinderkaurd/react-test -f ./client/Dockerfile.dev ./client
    
script:
    - docker run -e CI=true jagwinderkaurd/react-test npm test
    
after_success:
    - docker build -t jagwinderkaurd/multi-client ./client
    - docker build -t jagwinderkaurd/multi-nginx ./nginx
    - docker build -t jagwinderkaurd/multi-server ./server
    - docker build -t jagwinderkaurd/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push jagwinderkaurd/multi-client
    - docker push jagwinderkaurd/multi-nginx
    - docker push jagwinderkaurd/multi-server
    - docker push jagwinderkaurd/multi-worker  
